# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_connection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15node_connection.proto\x12\x0enodeconnection\"`\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"2\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\xb0\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\x31\n\x07\x65ntries\x18\x05 \x03(\x0b\x32 .nodeconnection.OperationDetails\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"E\n\x10OperationDetails\x12\x11\n\toperation\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\xbc\x01\n\x0eNodeConnection\x12J\n\x0brequestVote\x12\x1b.nodeconnection.VoteRequest\x1a\x1c.nodeconnection.VoteResponse\"\x00\x12^\n\rappendEntries\x12$.nodeconnection.AppendEntriesRequest\x1a%.nodeconnection.AppendEntriesResponse\"\x00\x42\x17\x42\x13NodeConnectionProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_connection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\023NodeConnectionProtoP\001'
  _VOTEREQUEST._serialized_start=41
  _VOTEREQUEST._serialized_end=137
  _VOTERESPONSE._serialized_start=139
  _VOTERESPONSE._serialized_end=189
  _APPENDENTRIESREQUEST._serialized_start=192
  _APPENDENTRIESREQUEST._serialized_end=368
  _APPENDENTRIESRESPONSE._serialized_start=370
  _APPENDENTRIESRESPONSE._serialized_end=424
  _OPERATIONDETAILS._serialized_start=426
  _OPERATIONDETAILS._serialized_end=495
  _NODECONNECTION._serialized_start=498
  _NODECONNECTION._serialized_end=686
# @@protoc_insertion_point(module_scope)
